### ISSUE TITLE
Problem with A10 device

### ISSUE THREAD

**Issue by Khaxio** [Hoodlab/retrofit-mvvm-#1]
Hi!,

just to let you know I find some issues running your project with an A10 device. I checked this link where explain how to solve. For me project works smoothly after running option 1 and 3 . Thanks for your programs, i really  learn a lot from them
hitting the URL with "https://" instead of "http://"

<?xml version="1.0" encoding="utf-8"?>
<manifest ...>
    <uses-permission android:name="android.permission.INTERNET" />
    <application
        ...
        **android:networkSecurityConfig="@xml/network_security_config"**
        ...>
        ...
    </application>
</manifest>

**Comment by Hoodlab** [comment]
Thanks for the feedback
